-- MySQL Script generated by MySQL Workbench
-- Fri May 23 10:09:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema solarPanel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `solarPanel` ;

-- -----------------------------------------------------
-- Schema solarPanel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solarPanel` DEFAULT CHARACTER SET utf8 ;
USE `solarPanel` ;

-- -----------------------------------------------------
-- Table `solarPanel`.`can_frames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `solarPanel`.`can_frames` ;

CREATE TABLE IF NOT EXISTS `solarPanel`.`can_frames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `east` INT NULL,
  `west` INT NULL,
  `north` INT NULL,
  `average` INT NULL,
  `v_panel` INT NULL,
  `v_battery` INT NULL,
  `c_panel` INT NULL,
  `c_battery` INT NULL,
  `charge_state` VARCHAR(255) NULL,
  `light_on` INT NULL,
  `light_lvl` INT NULL,
  `curr_elev` INT NULL,
  `curr_azim` INT NULL,
  `angle_azim` INT NULL,
  `angle_elev` INT NULL,
  `corr_mode` INT NULL,
  `corr_interval` INT NULL,
  `corr_threshold` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarPanel`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `solarPanel`.`login` ;

CREATE TABLE IF NOT EXISTS `solarPanel`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarPanel`.`reset_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `solarPanel`.`reset_password` ;

CREATE TABLE IF NOT EXISTS `solarPanel`.`reset_password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` DATETIME NOT NULL,
  `used` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
